### ISSUE TITLE
What do you need from pdftk_forms ? (Roadmap)

### ISSUE THREAD

**Issue by elmatou** [tcocca/active_pdftk#10]
Pdftk can operate all these tasks : 
from http://www.pdflabs.com/docs/pdftk-man-page/
[ cat | shuffle | burst | generate_fdf | fill_form | background | multibackground | stamp | multistamp | dump_data | ump_data_utf8 | dump_data_fields | dump_data_fields_utf8 | update_info | update_info_utf8 | attach_files | unpack_files ]

We support already (or plan to *):
generate_fdf (by our means)
fill_form
dump_data
*dump_data_utf8
- stamp (for my personal needs)
- update_info (for my personal needs)
- update_info_utf8 (for my personal needs)
- attach_files (for my personal needs)

**Comment by tcocca** [comment]
What do you need?  Literally I built this to read an editable pdf to get the fields so I could create an HTML form for people to fill out and then get an 'completed' pdf from their input back.  So All I needed was dump_data_fields and fill_form.  Do you need anything else? 

I don't mind supporting any/all of the functions.  I figured I'd get to them as needed but wasn't putting a priority on stuff I was never gonna use. But it would be nice to have a complete wrapper.

**Comment by elmatou** [comment]
Xposting here because it make more sens :
I'm talking of abilities of pdftk.
It does not only fill forms, it allow to manipulate PDF files.
Attaching any file (html, jpg, fonts, ... anything) to a specific PDF file, even to a specific page.
Concatenating files, mean build a new PDF with two or more input files by attaching them one after another.
I think it could be in the scope of this library because it needs wrapping around pdftk, even if it doesn't speak really about forms. Once we have a powerfull wrapper, any abstraction layer could use it to perform all pdftk actions

**Comment by tcocca** [comment]
We now support the full list of commands and any options that aren't interactive in the master branch
