### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by elmatou** [tcocca/active_pdftk#13]
We should write an inline documentation.
We have to choose the documentation engine for this lib.
Choices are :
- Rdoc http://rdoc.sourceforge.net/
- Sdoc (upon Rdoc) http://railsapi.com/
- YARD http://rubydoc.info/
- ...

**Comment by tcocca** [comment]
YARD is what we decided on

**Comment by tcocca** [comment]
Merged in your YARD setup with the documentation for Call and Form, need to keep working on the rest of the classes.

**Comment by tcocca** [comment]
Need to Re-write the Readme for the new "version", Update the Changelog

**Comment by elmatou** [comment]
I did it in my pull request,
but you can do what ever you want with it.

**Comment by tcocca** [comment]
Ah, cool, I'll merge that stuff tonight.  Also, going to try and get yardoc macros working for the Wrapper class, as its mostly reusable.
