### ISSUE TITLE
pdftk library setting / detection

### ISSUE THREAD

**Issue by elmatou** [tcocca/active_pdftk#5]
Create a class variable for the pdftk path in order to set it only once.

Maybe we could code an autodetection strategy for the library.
on unix system it is quite simple:

```
pdftk_path = %x{locate pdftk | grep "/bin/pdftk"}.strip
```

**Comment by elmatou** [comment]
My proposal is :

``` ruby
module PdftkForms
  class Wrapper
    def initialize(pdftk_path = nil, options = {})
      @path = Wrapper.path
      @options = options
      raise(MissingLibrary, "Pdftk library not found on your system, please check the binary path or fetch it at http://www.pdflabs.com/tools/pdftk-the-pdf-toolkit/") if pdftk_version.to_f == 0
    end

    class << self

      @@path = locate_pdftk || 'pdftk'

      def path
        @@path
      end

      def path=(value)
        @@path = value
      end

      private

      # Try to locate the library
      def locate_pdftk
        pdftk_path = %x{locate pdftk | grep "/bin/pdftk"}.strip # should work on all unix system
        pdftk_path = nil if pdftk_path.empty?
        # TODO find a valid Win32 procedure (not in my top priorities)
#        pdftk_path ||= %x{cd \ && dir pdftk.exe \S \B}.strip
      end

    end
```

If you are ok, I start a new branch with it.

**Comment by tcocca** [comment]
in the locate_pdftk method i think we should just use:   %x{which pdftk}.strip

locate seems to pull up anything that matches pdftk and i'm not sure the grep is the best solution in that case.

I also want to continue to allow people to set the path manually instead of relying on the unix calls.

also why the use of the @@ class variables?

**Comment by elmatou** [comment]
Hi Tom,
'which' unix command look in $PATH to give the path of an executable. That is not what we intend to do (if it is in the $PATH we don't care about full path.)
'locate' search for martching path (file & directory), 'grep' extract from the list the file included in bin directory (as it is packed for this software).

Me too I want people to be able to set the path. That is why I implemented setter and getter for class variable

```
PdftkForms::Wrapper.path = '/path/to/binary'
```

A class variable ? because we set the path only once, for all later use of the gem.

**Comment by tcocca** [comment]
yup, you are correct, so it should be more like this I think

``` ruby
module PdftkForms
  class Wrapper
    def initialize(pdftk_path = nil, options = {})
      Wrapper.path = pdftk_path unless pdftk_path.nil?
      @options = options
      raise(MissingLibrary, "Pdftk library not found on your system, please check the binary path or fetch it at http://www.pdflabs.com/tools/pdftk-the-pdf-toolkit/") if Wrapper.path.nil?
    end

    class << self
      @@path = locate_pdftk || 'pdftk'

      def path
        @@path
      end

      def path=(value)
        @@path = value
      end

      private

      # Try to locate the library
      def locate_pdftk
        pdftk_path = %x{locate pdftk | grep "/bin/pdftk"}.strip # should work on all unix system
        pdftk_path = nil if pdftk_path.empty?
        # TODO find a valid Win32 procedure (not in my top priorities)
        # pdftk_path ||= %x{cd \ && dir pdftk.exe \S \B}.strip
      end
    end

    private

    def call_pdftk(*args)
      %x{#{Wrapper.path} #{args.flatten.compact.join ' '}}
    end

  end
end
```

Thoughts?

~ Tom

**Comment by tcocca** [comment]
The windows piece will be tricky, not sure how to handle that at all.  Lets focus on *NIX for now and then see if some windows user is kind enough to patch for us maybe?

~ Tom

**Comment by elmatou** [comment]
Hi Tom,
I totally agree with you on the windows topic, if somebody need it he will implement it with his knowledge of Windows cmd.

I also want the ability to set a particular path for an `Wrapper` instance.
Just implementing the tests, I'll send you a pull request to discuss on solid matter.

**Comment by tcocca** [comment]
Merged your pull request in tonight, I guess there were 2 issues for this since the pull request opened another.
