### ISSUE TITLE
PdftkForms::Field control imputs

### ISSUE THREAD

**Issue by elmatou** [tcocca/active_pdftk#9]
I'm not yet very aware of abilities of PDF forms,
but I think we should control what we send as inputs value to pdftk
PftkForms::Field#value= should implement the logic

**Comment by tcocca** [comment]
So, PDF is completely annoying. All the "meta data" for fields are set in the FieldFlags integer that gets returned when you dump data fields.  This integer is the base 10 representation of a binary string.  Each bit is representative of a small piece of information about that field, combining this with the FieldType (one of 'Button', 'Text' or 'Choice') you can figure out what the field is.

Based on a bunch of research (here: http://www.verypdf.com/document/pdf-format-reference/) I have found the following documentation:

The number is the bit in that case so "2" is "10"

```
All Fields:
1 - ReadOnly - If set the user may not change the value of the field. Any associated widget annotations will not interact with the user; that is, they will not respond to mouse clicks or change their appearance in response to mouse motions. This flag is useful for fields whose values are computed or imported from a database.
2 - Required - If set the field must have a value at the time it is exported by a submit-form action.
3 - NoExport - If set the field must not be exported by a submit-form action.

Text Fields Only:
13 - Multiline - If set the field can contain multiple lines of text; if clear, the field’s text is restricted to a single line.
14 - Password - If set the ﬁeld is intended for entering a secure password that should not be echoed visibly to the screen. Characters typed from the keyboard should instead be echoed in some unreadable form, such as asterisks or bullet characters. To protect password confidentiality, viewer applications should never store the value of the text ﬁeld in the PDF file if this flag is set. 
21 - FileSelect (PDF 1.4) - If set the text entered in the field represents the pathname of a file whose contents are to be submitted as the value of the field.
23 - DoNotSpellCheck (PDF 1.4) - This flag is meaningful only if the Combo and Edit flags are both set. If set text entered in the field is not spell-checked.
24 - DoNotScroll (PDF 1.4) - If set the field does not scroll (horizontally for single-line fields, vertically for multiple-line fields) to accommodate more text than fits within its annotation rectangle. Once the field is full, no further text is accepted.
25 - Comb (PDF 1.5) - Meaningful only if the MaxLen entry is present in the text field and if the Multiline, Password, and FileSelect flags are clear. If set the field is automatically divided into as many equally spaced positions, or combs, as the value of MaxLen, and the text is laid out into those combs.
26 - RichTex (PDF 1.5) - If set the value of this field should be represented as a rich text string. If the field has a value, the entry of the field dictionary specifies the rich text string.

Choice Fields Only:
18 - Combo - If set the ﬁeld is a combo box; if clear, the ﬁeld is a list box. 
19 - Edit - This flag is meaningful only if the Combo flag is set. If set the combo box includes an editable text box as well as a drop down list; if clear, it includes only a drop down list.
20 - Sort - If set the ﬁeld’s option items should be sorted alphabetically. This flag is intended for use by form authoring tools, not by PDF viewer applications; viewers should simply display the options in the order in which they occur in the Opt array. 
22 - MultiSelect (PDF 1.4) - If set more than one of the ﬁeld’s option items may be selected simultaneously; if clear, no more than one item at a time may be selected. 
27 - CommitOnSelChange (PDF 1.5) - If set the new value is committed as soon as a selection is made with the pointing device. This option enables applications to perform an action once a selection is made, without requiring the user to exit the field. If clear, the new value is not committed until the user exits the field.

Button Fields Only:
16 - Radio - This flag is meaningful only if the Pushbutton flag is clear. If set the ﬁeld is a set of radio buttons; if clear, the ﬁeld is a checkbox.
17 - Pushbutton - If set, the ﬁeld is a pushbutton that does not retain a permanent value.

Radio Buttons Only:
15 - NoToggleToOff - If set exactly one radio button must be selected at all times; clicking the currently selected button has no effect. If set, clicking the selected button deselects it, leaving no button selected.
26 - RadiosInUnison (PDF 1.5) - If set a group of radio buttons within a radio button field that use the same value for the on state will turn on and off in unison; that is if one is checked, they are all checked. If clear, the buttons are mutually exclusive (the same behavior as HTML radio buttons).

NOTE:  Rich Text for Text Fields and Radios in Unison for radio buttons are both bit 26 (PDF Spec is awesome!)
```

I use some of this in the field class but it is by no means complete.  Also, we should actually consider what we need to support through that class, some of this obviously can not be handled appropriately.  A bunch of it can be (read-only, password, etc...)

**Comment by tcocca** [comment]
Some thoughts,

I already handle ReadOnly, Required, Multiline, Radio, Pushbutton.

I am planning on getting in support for Password (set the #field_type method to 'password_field' to match rails, and 'FileSelect' which will set #field_type to 'file_field' to match rails).

I am working on getting the multiselect support in.  I am going to keep the #field_type as select but just add an additional method which is #multiselect?

Combo and Edit fields will be a little tricky.

Combo box is a select that shows multiple values at once with a scroll bar, list box is a regular dropdown.  Should we handle this?  Maybe the same type of thing as #multiselect?  Still return 'select' as the #field_type but add an additional method #combo_box? which will give the front end developer the information they need for how to write the html for the form.

Edit gives a text field AND a dropdown so if you value you want is not in the dropdown you can just type it in.  Not sure how to handle that situation.

Sort can be ignored as it is only for form authoring tools.

I think we can ignore DoNotSpellCheck, DoNotScroll and Comb for now (these are all mainly display issues).  RichText I am not sure about, how would we handle this?  CommitOnSelChange can also be ignored in my opinion as this is a display piece.

Should we handle the 2 radio button options? Any thoughts there?

~ Tom

**Comment by elmatou** [comment]
Hum... tricky topic.
First off all what is our target, what is our scope (My needs are only filling form, attaching files, concatenate files).
If pdftk_forms is a wrapper, we should stop once we retrieved the PDF field type (all of them) and there respective options, and no need to take care of Rails or HTML conversion. With the options we alter the logic of the field (selectable, writable, readable, checkable, ...).
If understand your specs extract, we have 4 field types, with several options available.
`@field.type #=> one of the 4 types`
`@options #=> an Array of options`

But, it is maybe not far enough for some users (users ? where ? who ?).
If we want to map the fields type, we should do it in another adapter class (eg : `ActivePdf::Fields < PdftkForms::Fields`, with a `to_s` method rendering the field for rails), and a specific adapter, should be written for each rendering technology (Rails (using helper), HTML, JQuery, Prototype, ...) and each adapter will render as best as he can the field type and options.

Here are my thoughs, I pretty sure we have, for the core of the library, to stick to PDF issues, and let the abstract rendering to higher (and more specific) layers.

Regards, Marco

**Comment by tcocca** [comment]
Right, I think we only need to go so far as exposing the field_type and the options for the field.  People can write helpers to make interacting with the field_type easier (which I have done in my own app that this was built for).  The key is to provide the #field_type method with types that correspond to rails form_builder helper methods.

So, PDF give you one of 3 types of fields:  'Text', 'Button', 'Choice'.

I expand those out based on the flag options in the #field_type method currently, so 'Button' turns into 1 of 'radio_button', 'check_box', 'push_button' (this one doesn't correspond but there is nothing - this is the dumbest form field ever, its just a button doesn't have a value and can't insert a value - I hate pdf).

So, I think I need to expand 'Text' further.  Instead of just 'text_field' or 'text_area' I need to support 'file_field' (takes a path to a file) and 'password_field'.

Other than those 2 additional, I think the only other pieces I will add for now are the 'multiselect' for select fields and maybe 'edit' which says if you can have a text field in addition to the select dropdown list to add your own value.

But as far as this library takes it I am only adding methods to get booleans for these options.  It wont be providing any front end form builder helpers or views or anything like that at all (although it would be nice to have this eventually abstracted out to a library of some type built for rails)

**Comment by tcocca** [comment]
By the way what do you mean 'attaching files' as a requirement?  Attaching files to what?  The pdf you are generating?  Or attaching the generated pdfs to something else (some other model or something)?

Also, what do you mean concatenating files?

If it is the later, then this lib wont be doing any of that as there are plenty of things like paperclip/carrierwave, etc...

**Comment by elmatou** [comment]
I'm talking of abilities of pdftk.
It does not only fill forms, it allow to manipulate PDF files.
Attaching any file (html, jpg, fonts, ... anything) to a specific PDF file, even to a specific page.
Concatenating files, mean build a new PDF with two or more input files by attaching them one after another.
I think it could be in the scope of this library because it needs wrapping around `pdftk`, even if it doesn't speak really about forms. Once we have a powerfull wrapper, any abstraction layer could use it to perform all `pdftk` actions

**Comment by tcocca** [comment]
Yeah, ok.  As long as it is something pdftk does 'naturally' I have no problem with it (even if its not related to forms).  Also, changing the name of the lib is something I am not completely against.  There was already the 'pdftk' project I 'forked' from but it is pretty dead as of now.  pdftk_forms seems reasonable though.  Also, I'm not very creative with gem names like some people are.  I'd rather just make the things work ...

Anyway, thanks again for all the input help on this thing.  This should turn out to be a great project.

**Comment by elmatou** [comment]
I definitely love the OpenSource concept.
I maybe a dreamer, but I'm quite sure, it will become the futur for IT business model. will see.

**Comment by elmatou** [comment]
What do you think about `Field#build` for parsing data_fields ?

``` ruby
PdftkForms::Field.build(
"FieldType: Button
FieldName: radio_button
FieldFlags: 49152
FieldJustification: Left
FieldStateOption: No
FieldStateOption: Off
FieldStateOption: Yes") #=> <#PdftkForms::Fields.......>
```

**Comment by tcocca** [comment]
What would this be for?  or I guess when would you use this?

**Comment by elmatou** [comment]
I'll use it in the wrapper, in order to put Field logic in the Field class.
For now we instantiate a Field object with a hash, but in our context it make also sens to build it with the PDF formated string.
It is only a matter of organization, maintainability of the code, no big deal if you don't want it.

Extracting your wrapper code

``` ruby
    def build(field_text)
        attributes = {}
        field_text.scan(/^(\w+): (.*)$/) do |key, value|
          if key == "FieldStateOption"
            attributes[key] ||= []
            attributes[key] << value
          else
            attributes[key] = value
          end
        end
        new(attributes)
   end
```

**Comment by tcocca** [comment]
Gotcha, no thats cool.  It definitely belongs in the Field class, just not sure we should call it as a class method on Field and then call new at the end.  Or keep calling PdftkForms::Field.new and pass it the string and then have the initialize method call build as an instance method or something?

Thoughts?

~ Tom

PS. really busy weekend, didn't get a chance to look at the other stuff but I will.  I'm gonna shoot you an email (gmail) off of github.

**Comment by tcocca** [comment]
The field class is now complete and par of the master branch.
